version: "2"
services:
    web:
        build: ./web
        #image: web_php
        ports: 
            - "8001:80"
        volumes:
            - dbinit:/dbinit
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5
        ports:
            - "33060:3306"
        environment:
            MYSQL_DATABASE: web_db
            MYSQL_USER: web_user
            MYSQL_PASSWORD: web_pass
            MYSQL_ROOT_PASSWORD: root 
        volumes:
            - dbinit:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on: 
            - db
        ports:
            - "8000:80"
        environment:
            MYSQL_USER: web_user
            MYSQL_PASSWORD: web_pass
            MYSQL_ROOT_PASSWORD: root
volumes:
    dbdata:
    dbinit:
